version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/var/www/html/index.html
    depends_on:
      - nodejs
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
